import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/container/Header/Header";
import Image from "next/image";
import Icon from "@/assets/vercel.svg";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header>
          <div className="container mx-auto flex justify-between items-center">
            <div className="flex items-center gap-4">
              <Image src={Icon} alt="logo" width={20} height={20} />
              <a className="text-lg font-bold">Slide Builder</a>
            </div>
            <div className="inline-flex items-center justify-center w-10 h-10 text-xl text-white bg-indigo-500 rounded-full">
              H
            </div>
          </div>
        </Header>
        <main className="container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
